source 'https://rubygems.org'
gem 'sinatra'
gem 'pg'
gem 'activesupport'
gem 'thinking-sphinx'
gem 'ts-delayed-delta', '1.1.3', :require => 'thinking_sphinx/deltas/delayed_delta' 
gem 'ts-datetime-delta', :require => 'thinking_sphinx/deltas/datetime_delta'
